
return {
	BLOCK_SIZE = 32,
	SHOP_BLOCK_SIZE = 19.2,
	MAP_WIDTH = 16,
	WORLD_X = 32,
	WORLD_Y = 32,
	TRIGGER_OFFSET = 20,
	BLOCK_SPAWN_SPAN = 45,
	WORLD_SCREEN_X = 32,
	METRES_PER_TILE = 1, --5,
	REFRESH_COST = 75,
	PIECE_WIN_DISTANCE = 216,
}
