local pieceDefs = {
	{
		name = "1I",
		tiles = {
			{0, 0},
		},
		carveStrength = 1,
		imageFile = "1I",
		desc = "Is this even worth it?",
	},
	{
		name = "2I",
		tiles = {
			{0, 0},
			{1, 0},
		},
		carveStrength = 1,
		imageFile = "2I",
		desc = "At least it's not a single tile.",
	},
	{
		name = "3I",
		tiles = {
			{-1, 0},
			{0, 0},
			{1, 0},
		},
		carveStrength = 1,
		imageFile = "3I",
		desc = "A bit of reach, but not much.",
	},
	{
		name = "3L",
		tiles = {
			{0, 0},
			{0, 1},
			{1, 0},
		},
		carveStrength = 1,
		imageFile = "3L",
		desc = "An elbow.  A shape more suited to pasta than mining.",
	},
	{
		name = "4I",
		tiles = {
			{-1, 0},
			{0, 0},
			{1, 0},
			{2, 0},
		},
		carveStrength = 1,
		imageFile = "4I",
		desc = "A long piece for a deep mine",
	},
	{
		name = "4S",
		tiles = {
			{-1, 1},
			{0, 0},
			{1, 0},
			{0, 1},
		},
		carveStrength = 1,
		imageFile = "4S",
		desc = "An S shaped piece.  Not to be confused with the Z piece.",
	},
	{
		name = "4Z",
		tiles = {
			{-1, 0},
			{0, 1},
			{0, 0},
			{1, 1},
		},
		carveStrength = 1,
		imageFile = "4Z",
		desc = "A Z shaped piece.  Not to be confused with the S piece.",
	},
	{
		name = "4L",
		tiles = {
			{-1, 0},
			{-1, 1},
			{0, 0},
			{1, 0},
		},
		carveStrength = 1,
		imageFile = "4L",
		desc = "A stick with a handle on it.",
	},
	{
		name = "4J",
		tiles = {
			{-1, 0},
			{1, 1},
			{0, 0},
			{1, 0},
		},
		carveStrength = 1,
		imageFile = "4J",
		desc = "To reach out and hook that bit of gold.",
	},
	{
		name = "4O",
		tiles = {
			{1, 0},
			{1, 1},
			{0, 0},
			{0, 1},
		},
		carveStrength = 1,
		imageFile = "4O",
		desc = "A bit of a dumpling, but at least it tessellates well.",
	},
	{
		name = "4T",
		tiles = {
			{-1, 0},
			{0, 1},
			{0, 0},
			{1, 0},
		},
		carveStrength = 1,
		imageFile = "4T",
		desc = "Such T.  Many Symmetry.  Wow.",
	},
	{
		name = "5O",
		tiles = {
			{-2, 0},
			{-1, 0},
			{0, 0},
			{1, 0},
			{2, 0},
		},
		carveStrength = 1,
		imageFile = "5O",
		desc = "The longest piece money can buy.",
	},
	{
		name = "5PR",
		tiles = {
			{-1, 0},
			{0, 0},
			{1, 0},
			{0, 1},
			{-1, 1},
		},
		carveStrength = 1,
		imageFile = "5P",
	},
	{
		name = "5PL",
		tiles = {
			{-1, 0},
			{0, 0},
			{1, 0},
			{0, 1},
			{1, 1},
		},
		carveStrength = 1,
		imageFile = "5P",
	},
	{
		name = "5L",
		tiles = {
			{-1, 0},
			{0, 0},
			{1, 0},
			{2, 0},
			{-1, 1},
		},
		carveStrength = 1,
		imageFile = "5L",
	},
	{
		name = "5J",
		tiles = {
			{-1, 0},
			{1, 0},
			{0, 0},
			{-2, 0},
			{1, 1},
		},
		carveStrength = 1,
		imageFile = "5J",
	},
	{
		name = "5RL",
		tiles = {
			{-1, 0},
			{0, -1},
			{0, 0},
			{0, 1},
			{1, -1},
		},
		carveStrength = 1,
		imageFile = "5RL",
	},
	{
		name = "5RR",
		tiles = {
			{1, 0},
			{0, -1},
			{0, 0},
			{0, 1},
			{-1, -1},
		},
		carveStrength = 1,
		imageFile = "5RR",
	},
	{
		name = "5SL",
		tiles = {
			{-2, 0},
			{-1, 0},
			{0, 0},
			{0, 1},
			{1, 1},
		},
		carveStrength = 1,
		imageFile = "5SL",
	},
	{
		name = "5SR",
		tiles = {
			{0, 0},
			{1, 0},
			{2, 0},
			{0, 1},
			{-1, 1},
		},
		carveStrength = 1,
		imageFile = "5SR",
	},
	{
		name = "5T",
		tiles = {
			{-1, -1},
			{0, -1},
			{1, -1},
			{0, 0},
			{0, 1},
		},
		carveStrength = 1,
		imageFile = "5T",
	},
	{
		name = "5U",
		tiles = {
			{-1, 0},
			{0, 0},
			{1, 0},
			{-1, 1},
			{1, 1},
		},
		carveStrength = 1,
		imageFile = "5U",
		desc = "Gets a lot of tiles, but leaves a gap in the middle.",
	},
	{
		name = "5V",
		tiles = {
			{-1, -1},
			{0, -1},
			{1, -1},
			{-1, 0},
			{-1, 1},
		},
		carveStrength = 1,
		imageFile = "5V",
	},
	{
		name = "5W",
		tiles = {
			{0, 0},
			{0, -1},
			{1, -1},
			{-1, 0},
			{-1, 1},
		},
		carveStrength = 1,
		imageFile = "5W",
	},
	{
		name = "5X",
		tiles = {
			{0, -1},
			{0, 0},
			{1, 0},
			{-1, 0},
			{0, 1},
		},
		carveStrength = 1,
		imageFile = "5X",
	},
	{
		name = "5YL",
		tiles = {
			{-1, 0},
			{0, 0},
			{1, 0},
			{2, 0},
			{0, 1},
		},
		carveStrength = 1,
		imageFile = "5YL",
	},
	{
		name = "5YR",
		tiles = {
			{-1, 0},
			{0, 0},
			{1, 0},
			{-2, 0},
			{0, 1},
		},
		carveStrength = 1,
		imageFile = "5YR",
	},
	{
		name = "5ZL",
		tiles = {
			{-1, 0},
			{0, 0},
			{1, 0},
			{1, -1},
			{-1, 1},
		},
		carveStrength = 1,
		imageFile = "5ZL",
	},
	{
		name = "5ZR",
		tiles = {
			{-1, 0},
			{0, 0},
			{1, 0},
			{-1, -1},
			{1, 1},
		},
		carveStrength = 1,
		imageFile = "5ZR",
	},
}

pieceDefs.names = {}
for i = 1, #pieceDefs do
	pieceDefs.names[pieceDefs[i].name] = pieceDefs[i]
end

return pieceDefs
